name: build dist

on:
  create:
    tags:

jobs:
  linux-build:
    name: build on linux
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: apt update
      run: |
        sudo apt-get update
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: setup gpg necessities
      run: sudo bash -c "echo '$GPG_KEY_CONTENTS' | base64 -d > '$SIGNING_SECRET_KEY_RING_FILE'"
      env:
        GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}
        SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
    - name: rewrite build.gradle to require signing
      run: |
        sed -i "s/signing {}/signing { sign(publishing.publications) }/" compose-mpp/build.gradle.kts
    - name: publish
      run: ./gradlew --warning-mode all publish dokkaHtml
      env:
        OSSRH_USERNAME: atsushieno
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
    - name: upload build failure logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-failure-logs
        path: |
          compose-mpp/build/reports/
    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: compose-mpp-artifacts
        path: |
          compose-mpp/build/libs/*.jar
          compose-mpp/build/outputs/aar/*.aar
    - name: deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.2
      with:
        branch: gh-pages
        folder: missingdot/build/dokka/html
